# Generated by Django 5.2.5 on 2025-08-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_image_basketitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
